CREATE DATABASE IF NOT EXISTS `Users`
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS `Data`
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON `Users`.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON `Data`.* TO 'root'@'%';

-- 刷新权限
FLUSH PRIVILEGES;