// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package common

import (
	"fmt"
)

type Resp struct {
	Code     int16  `thrift:"code,1" frugal:"1,default,i16" json:"code"`
	HttpCode int16  `thrift:"http_code,2" frugal:"2,default,i16" json:"http_code"`
	Message  string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewResp() *Resp {
	return &Resp{}
}

func (p *Resp) InitDefault() {
}

func (p *Resp) GetCode() (v int16) {
	return p.Code
}

func (p *Resp) GetHttpCode() (v int16) {
	return p.HttpCode
}

func (p *Resp) GetMessage() (v string) {
	return p.Message
}
func (p *Resp) SetCode(val int16) {
	p.Code = val
}
func (p *Resp) SetHttpCode(val int16) {
	p.HttpCode = val
}
func (p *Resp) SetMessage(val string) {
	p.Message = val
}

func (p *Resp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Resp(%+v)", *p)
}

var fieldIDToName_Resp = map[int16]string{
	1: "code",
	2: "http_code",
	3: "message",
}
